var Q = require('q');
var fs = require('fs');

var search = require('./search');
var updater = require('./updater');

console.log('\n~~~~~~~~ This script will read the isbn numbers in the json file and retrieve its information ~~~~~~~~');
search.promptForJSON('What is the JSON file generated by the SFU DB Updater?')
    .then(function(file) {
	console.log('Reading - ' + file);
	return updater.readCourses(file);
    })
    .then(function(file) {
	console.log('Retreiving Book Data');
	return updater.parseTextbooks(file);
    })
    .then(function(file) {
	console.log('Outputing to JSON file');
	return updater.writeBooksToJSON(file);
    })
    .done(function() {
        console.log('\n~~~~~~~~ Script Complete ~~~~~~~~');
        process.exit(0);
    });
